In [1]:
import numpy as np
import math as math
import pandas as pd

In [2]:
#Q1
arr=np.array([2,3,5,3,2,1,4,5,6,7])

In [3]:
arr


array([2, 3, 5, 3, 2, 1, 4, 5, 6, 7])

In [4]:
def mean(arr,s):
    for e in arr:
        s+=e
    return s/len(arr)
    

In [5]:
x_mean=mean(arr,0)

In [6]:
x_mean


3.8

In [7]:

def var(arr,mean,s):
    for e in arr :
        s+=(e-mean)**2
    
    
    return s/(len(arr)-1)
    

In [8]:
print(var(arr,x_mean,0))

3.7333333333333334


In [9]:
r2=np.var(arr)
r2

3.3599999999999994

In [10]:
#Q2
arr1=np.array([4,5,2,2,3,4,6,7])

In [11]:
arr2=np.array([2,3,4,3,7,9,5,4])

In [12]:
arr1_mean=mean(arr1,0)

In [13]:
arr2_mean=mean(arr2,0)

In [14]:
def covar(arr1,arr2,summ,arr1_mean,arr2_mean):
    n=len(arr1)
    for i in range (n):
        summ+= (arr1[i]-arr1_mean)*(arr2[i]-arr2_mean)
    
    return summ/(n-1)

In [15]:
covar(arr1,arr2,0,arr1_mean,arr2_mean)

-0.08928571428571429

In [16]:
#Q3
def correlation(arr1,arr2,summ,arr1_mean,arr2_mean):
    coVar=covar(arr1,arr2,0,arr1_mean,arr2_mean)
    varX=var(arr1,arr1_mean,0)
    varY=var(arr2,arr2_mean,0)
    denumerator=math.sqrt(varX*varY)
    return coVar/denumerator


In [17]:
correlation(arr1,arr2,0,arr1_mean,arr2_mean)

-0.021233576208613762

In [18]:
#Q4
newarr=np.array([[1,2,3,4,3,3,2],[1,2,4,2,5,2,4]])

In [19]:
mean1=mean(newarr[0],0)

In [20]:
mean1

2.5714285714285716

In [21]:
mean2=mean(newarr[1],0)

In [22]:
mean2

2.857142857142857

In [23]:
var1=var(newarr[0],mean1,0)

In [24]:
var1

0.9523809523809526

In [25]:
var2=var(newarr[1],mean2,0)

In [26]:
var2

2.142857142857143

In [27]:
covar(newarr[0],newarr[1],0,mean1,mean2)

0.42857142857142844

In [28]:
correlation(newarr[0],newarr[1],0,mean1,mean2)

0.2999999999999999

In [29]:
covarMatrix=np.cov(newarr[0],newarr[1])

In [30]:
covarMatrix


array([[0.95238095, 0.42857143],
       [0.42857143, 2.14285714]])

In [31]:
var(newarr[0],mean1,0)

0.9523809523809526

In [32]:
corrMatrix=np.corrcoef(newarr[0],newarr[1])

In [33]:
corrMatrix


array([[1. , 0.3],
       [0.3, 1. ]])